#! /bin/sh
#
# usage: runstatic [<testfile>...]
# without args, runs all *.test files in the current directory
#

ROUTE_SRC=../src
VEINS_SRC=$VEINS_HOME/src
OMNET_SRC=$OMNET_HOME/src
MAKEFRAG_=.extra/makefrag

MODE=${MODE:-"debug"}
MAKEOPTIONS="MODE=$MODE"
MAKE=${MAKE:-"make"}
NUMPROC=$(command -v nproc >/dev/null && nproc || echo 8)
export MAKEFLAGS=${MAKEFLAGS:-"-j"$NUMPROC}

case "$MODE" in
  "release") PROGSUFFIX="" ;;
  "debug") PROGSUFFIX="_dbg" ;;
  *) PROGSUFFIX="_$MODE" ;;
esac

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='**/*.test'; fi
if [ ! -d work ];  then mkdir work; fi
rm -rf work/lib
cp -pPR $OMNET_HOME/lib work/       # OSX dos not support cp -a

#export NEDPATH=.:../lib
EXTRA_INCLUDES="-I$OMNET_SRC -I$VEINS_SRC -I../$ROUTE_SRC"
#OPT="--debugger-attach-on-error=true"
#$MAKE $MAKEOPTIONS -C signalreg


opp_test gen -v --args $OPT -- $TESTFILES || exit 1
echo
(cd work; opp_makemake -f -o work --deep -i ../$MAKEFRAG_ $EXTRA_INCLUDES;
$MAKE $MAKEOPTIONS) || exit 1
echo
opp_test run -p work$PROGSUFFIX -v --args $OPT -- $TESTFILES || exit 1
echo
echo Results can be found in ./work

